version: '3.7'

services:

  node:
    build:
      context: .
      target: dev
    ports:
      - "4001:3000"
    volumes:
      - .:/app:delegated
    environment:
      - MongoURI=${MongoURI}
      - Redis_Hostname=${Redis_Hostname}
      - Redis_Password=${Redis_Password}
      - GOOGLE_CLIENT=${GOOGLE_CLIENT}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - TRACING_HOST=${TRACING_HOST}
    healthcheck:
      disable: true
    networks:
      - tiles-api

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - tiles-api

networks:
  tiles-api: